### ISSUE TITLE
Keep blank lines in reading mode

### ISSUE THREAD

**Issue by wuzhen97** [mugiwara85/CodeblockCustomizer#1]
Hello，for clearer code hierarchy,  you need to leave blank lines sometimes in the code block,  but the plug-in will swallow these blank lines. thanks~

editing view：

![image](https://user-images.githubusercontent.com/61906420/215080579-4703377f-db22-4471-aaaf-d15ce6f386e9.png)

rereading view：

![image](https://user-images.githubusercontent.com/61906420/215080620-8a106265-d009-4000-8da4-b30cac3ae86b.png)

**Comment by mugiwara85** [comment]
Hi! 
Oh, I made a small mistake as I see. I had this problem, but corrected it (apparently not fully). If you enable the line numbers, then it will be shown correctly. Fow now as a workaround. I will correct it, probably at the weekend.

**Comment by wuzhen97** [comment]
hi，thank you very much for your reply，and I look forward to your fix.

By the way, I suggest whether you can set the color of light and dark modes at the same time. Otherwise, when I switch the two modes, it will be a little cumbersome to switch the theme.

As most themes provide：

![image](https://user-images.githubusercontent.com/61906420/215086534-1536d40f-3661-4771-81a1-25832eb859e6.png)

thanks~

**Comment by mugiwara85** [comment]
Hi! What do you mean by "whether you can set the color of light and dark modes at the same time"? I don't really understand what you mean by that? Can you please explain a bit better?

**Comment by wuzhen97** [comment]
I know  you provide the default dark and light theme. 

but, I need to use light mode in the daytime and dark mode in the dark. 

so, it may be a little troublesome to switch them frequently. Can it follow the obsidian mode for adaptation？

**Comment by mugiwara85** [comment]
Oh yeah. That, I wanted to correct as well. I just haven't figured it out, how can I query which obsidian theme (dark or light) is selected currently. But I will look at this also at the weekend.

**Comment by mugiwara85** [comment]
hey, do you know by any chance a plugin, which changes its theme, if obsidians theme is changed? I would look at it, how they did it, so I can implement it as well.

**Comment by wuzhen97** [comment]
hello，I know one but it's by style setting plugin to set its color. You can try it and hope it will bring you inspiration：


- https://github.com/cumany/obsidian-floating-toc-plugin



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 28, 2023 22:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mugiwara85/CodeblockCustomizer] Keep blank lines in reading mode (Issue #1)




 
hey, do you know by any chance a plugin, which changes its theme, if obsidians theme is changed? I would look at it, how they did it, so I can implement it as well.

**Comment by wuzhen97** [comment]
this plugin is also with “style setting plugin” by the css to set its color：
- https://github.com/nothingislost/obsidian-hover-editor/blob/master/styles.css

**Comment by mugiwara85** [comment]
Hi! I released a new version (1.0.1), where the empty lines are now shown correctly in reading mode. I also changed a bit the theming. Now the themes will be set automatically according to Obsidians selected theme. I also added two toggles so you can save your theme as a default light or dark theme. I also updated a readme. Hope it is understandable. Please test, and give me a feedback.

**Comment by mugiwara85** [comment]
oh, and until I not forget, you might need to delete(just this once) the `<YourVault>\.obsidian\plugins\codeblock-customizer\data.json` file, since, I made some changes there as well.

**Comment by mugiwara85** [comment]
That's interesting. Did you delete the data.json file as I described above?

**Comment by wuzhen97** [comment]
> That's interesting. Did you delete the data.json file as I described above?

yeah，i deleted，but it automatically generates another one

**Comment by mugiwara85** [comment]
Yes, but that's OK. Just so i can reproduce the issue, what do you exactly do when the error is displayed? Switch obsidians theme from dark to light or adapt? Or do you change something else? I was testing for at least an hour but it worked for me.

**Comment by wuzhen97** [comment]
i installed it again，and found that the first switch worked fine，but then it stopped working。

And I found that the error only occurred when going from light to dark, but not the other way around

**Comment by wuzhen97** [comment]
I tested it once in the default configuration. I find that switching themes only works the first time。
and every time i reload a Markdown file， it will occurs the following error：

![image](https://user-images.githubusercontent.com/61906420/215384251-d38345b8-515a-45f6-949c-b5fdc18c0a43.png)

**Comment by wuzhen97** [comment]
I'm really sorry. I think I used it improperly. Now it works well. Although there are still some minor errors in the console. thanks~

![image](https://user-images.githubusercontent.com/61906420/215385077-41a8ad33-f4af-4adb-8738-7b9c799f1981.png)

**Comment by mugiwara85** [comment]
Is it working? What do you mean by "you used it improperly?"
