### ISSUE TITLE
Can't save the custom Settings

### ISSUE THREAD

**Issue by liuke101** [mugiwara85/CodeblockCustomizer#10]
Can't save the custom Settings, cause I lose my Settings when I switch themes or some other behavior

**Comment by mugiwara85** [comment]
which settings do you mean exactly?

**Comment by liuke101** [comment]
> which settings do you mean exactly?



> 

color Settings

**Comment by mugiwara85** [comment]
Which color setting???? Until you provide enough information or explain the problem I can't help. Describe the problem in a way so I can reproduce it.

**Comment by mugiwara85** [comment]
Yes, that is correct. If you only use one theme (for example dark), then you can change the colors, and they will stay as you selected. But if you are switching between themes, then you need to save your color settings in a theme. Give it a name, an save it. Also note, that you can also select if the theme is a default light or a default dark theme. This means, that if you change Obsidians theme (not the plugins theme), then the plugin will automatically select the default light/dark theme accordingly. I hope it is understandable. If not, just ask :)

![image](https://user-images.githubusercontent.com/65603765/235639225-f525e5e4-4f68-4b69-92cd-ba3ed746b503.png)
![image](https://user-images.githubusercontent.com/65603765/235639540-f6fda706-7bba-4815-89e8-b6ea9eb281b3.png)

**Comment by liuke101** [comment]
> Yes, that is correct. If you only use one theme (for example dark), then you can change the colors, and they will stay as you selected. But if you are switching between themes, then you need to save your color settings in a theme. Give it a name, an save it. Also note, that you can also select if the theme is a default light or a default dark theme. This means, that if you change Obsidians theme (not the plugins theme), then the plugin will automatically select the default light/dark theme accordingly. I hope it is understandable. If not, just ask :)
> 
> ![image](https://user-images.githubusercontent.com/65603765/235639225-f525e5e4-4f68-4b69-92cd-ba3ed746b503.png) ![image](https://user-images.githubusercontent.com/65603765/235639540-f6fda706-7bba-4815-89e8-b6ea9eb281b3.png)



> 

Thank you. I understand the logic of the setup.
