### ISSUE TITLE
I want the copy button and erase button to come out when I add language in live editor mode

### ISSUE THREAD

**Issue by Goldang1211** [mugiwara85/CodeblockCustomizer#100]
![image](https://github.com/user-attachments/assets/cb09f33a-5b62-45cd-b855-8749f6f00c9e)
![image](https://github.com/user-attachments/assets/cab3d38d-f302-40d6-99d3-9d0c5fde84e9)

I want the copy button and erase button to come out when I add language in live editor mode

**Comment by mugiwara85** [comment]
It should be already there. Which theme are you using?

**Comment by Goldang1211** [comment]
I using minimal theme

**Comment by mugiwara85** [comment]
@Goldang1211 Is the problem resolved? Or why did you close the issue? What caused the problem?

**Comment by Goldang1211** [comment]
I didn't close it first, but I solved it. It was a scroll longline option of minimal theme style setting
