### ISSUE TITLE
Request for additional word highlights

### ISSUE THREAD

**Issue by Goldang1211** [mugiwara85/CodeblockCustomizer#101]
Hello I'm using the plug-in so well.
I'd like to make a request for adding one function.
I've been using the word highlights
There are so many things that can't be done.
If you include the -,numbers, "",'',etc., you can't highlight it. Please do it

![image](https://github.com/user-attachments/assets/0cc546b2-30f8-4f52-bb9e-03238141b5ea)

**Comment by mugiwara85** [comment]
I already started working on it. If you want just take the main.js and styles.css and overwrites yours with it (after you created a backup). The new one would work as descrived in #92 and #93. I don't have a solution for specifying the " yet.

**Comment by mugiwara85** [comment]
Please read the updated line and text highlight in version 1.2.8. Should be fixed now.
