### ISSUE TITLE
[FR/Bug] Copy button for folded codeblocks

### ISSUE THREAD

**Issue by jobor019** [mugiwara85/CodeblockCustomizer#102]
Hi! Thanks for developing such a nice plugin!

In Live Preview / Editing View, it seems that the "copy code"-button isn't showing when the codeblock is folded. Is this intentional? Would it be possible to add this?

Folded (with mouse hovering, even though it doesn't show in the image):
<img width="500" alt="image" src="https://github.com/user-attachments/assets/5edcb369-5fd0-4b03-b86f-10924d9dd915">

Unfolded:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/0e249f81-e32b-44d6-b0aa-ed0a265785d9">

(In reading mode, it shows even when folded)
<img width="500" alt="image" src="https://github.com/user-attachments/assets/eff37914-8246-455d-8e4d-86476e679e4a">

(Settings):
<img width="500" alt="image" src="https://github.com/user-attachments/assets/d631f2e3-b3df-4137-bc6f-1653de34a1f7">
<img width="500" alt="image" src="https://github.com/user-attachments/assets/e4ec5ed8-a210-4ab2-af9f-a3a1b90869be">

**Comment by mugiwara85** [comment]
Hi!

No, I didn't notice it. I will correct it in the next release.

**Comment by mugiwara85** [comment]
@jobor019 quick question. (Please respond as soon as you can, because I want to release the new version soon.)

If the code block is collapsed:
- should the copy code button always be shown on the header, or only when hovered over the header? In reading mode it is only shown when hovered over the header. 
- if multiple buttons are enabled (delete code, and select code), should they also be displayed, or only the copy button? The select code, and delete code buttons would not make much sense, but the copy button I can understand that it should be displayed.

**Comment by jobor019** [comment]
Hmm, I think it's a good idea to stay consistent, so it should probably only show when hovered just like in the other modes.

For the delete/select code buttons, I don't use either of them so I cannot say, but your intuition make sense to me. I can't really understand why anyone would want to select folded code except for copying it. Again, it's probably a good idea to stay consistent with how you're currently handling this in the other modes

**Comment by mugiwara85** [comment]
I totally agree with you. I'll also add an option to always display the copy button when the header is collapsed, but by default it will only be displayed when hovered over the header.

**Comment by mugiwara85** [comment]
Hi @jobor019!

Sorry for the delay. Now it should work as follows:
- if code block is collapsed -> only copy button is displayed when you hover over the header
- if code block is uncollapsed -> all enabled buttons are displayed in header
- there is an additional option where you can enable if the buttons should be displayed (when the code block is uncollapsed) if the   cursor is inside a code block or not

I would be thankful if you could quickly test it and give me a feedback if everything works correctly. You can just overwrite the main.js and styles.css files (create a backup before).

**Comment by jobor019** [comment]
No worries, there's absolutely no rush on my side!

Great work, everything seems to be working exactly as you describe! 

<img width="675" alt="image" src="https://github.com/user-attachments/assets/066d91b4-7de8-44c8-9977-609539adf2f6">


Might be worth noting that it seems that all my settings for the plugin were wiped when copying it like that, even after restoring the old files. Obviously not a problem for me since I can just change them back in 5-10 min, but it might be a problem if this is something that happens to all users when you publish the next version of the plugin?

**Comment by mugiwara85** [comment]
All settings got restored? That's weird. I changed only the settings regarding the buttons. So only those settings should have been restored to default. I will definitely look into it. Thank you very much for your testing and Feedback. Release in 1-2 days.

**Comment by mugiwara85** [comment]
Available in version 1.2.8
