### ISSUE TITLE
Disable Folding

### ISSUE THREAD

**Issue by rgvillanueva28** [mugiwara85/CodeblockCustomizer#104]
Request to add a setting to disable folding so that the title will not fold when clicked.

**Comment by mugiwara85** [comment]
Just out of curiosity, why would you want this? Also, would you want this for all code blocks to apply, or just for specific ones?

**Comment by SmartFinn** [comment]
I want the same option because I sometimes accidentally clicked on the title of the block when trying to select the first line of the code.

**Comment by mugiwara85** [comment]
@rgvillanueva28 @SmartFinn Understood. I'll add it, and then the next release (today or tomorrow) will include it.

**Comment by mugiwara85** [comment]
@rgvillanueva28 @SmartFinn Just to be sure, this will result that you can't fold or unfold any code block. All code blocks remain uncollapsed at all times! Defining fold in the code block parameters or using the "Collapse all code blocks" command will absolutely not doing anything. 

Is this what you want?

**Comment by SmartFinn** [comment]
@mugiwara85 is it possible to disable folding for all blocks when `fold` and `unfold` parameters aren't set? This is the default that I expected.

**Comment by mugiwara85** [comment]
@SmartFinn Sure, that's why I asked, what exactly do you want :)
So, for code blocks where `fold` or `unfold` **is** specified the folding behavior should remain as is, but for other code blocks, where `fold` or `unfold` **is NOT** specified, it should be disabled, right?

**Comment by SmartFinn** [comment]
@mugiwara85 yes, it'll be great. Thanks

**Comment by mugiwara85** [comment]
@SmartFinn I added the option (in the Header settings page). If you could quickly try it out if everything works as it should, I could release it today. You can just take the `main.js` and `styles.css` and overwrite yours with it (create a backup before, and from the `data.json` as well)

**Comment by mugiwara85** [comment]
Available in version 1.2.8
