### ISSUE TITLE
[Feature request] Implement support for Obsidian Shiki plugin

### ISSUE THREAD

**Issue by RaporLoLpro** [mugiwara85/CodeblockCustomizer#106]
Hey, i think many people could like the functionality of your plugin (code wrap, icons, folding etc) but with proper and **consistent syntax highlight** 

I have found this plugin https://github.com/mProjectsCode/obsidian-shiki-plugin/ which does syntax highlight perfectly and for both **Live preview** and **Reading view** mods while Codeblock Customizer and Code Styler provides great QoL but no consistent syntax resolver. 

Is it possible to implement syntax solution from Shiki plugin but keep rest of QoL features Codeblock Customizer provides?

Thanks

**Comment by mugiwara85** [comment]
Hi,

First a little background: Obsidian uses CodeMirror 6 (this is an editor) in editing mode, which provides its own syntax highlighting, and uses Prism.js for reading mode for syntax highlighting. This is the reason why the syntax highlighting is not identical. This is completely an Obsidian thing. It is also very important to note that the editing mode and reading mode are totally different! They have nothing in common.

I looked at Shiki plugin. What the plugin does in editing mode is that it basically renders the code blocks to a html, applies its own syntax highlighting, and displays it in the editing mode. The problem with this approach is that you lose all the benefits of an editor. This is the reason why you can't click directly into a code block in editing mode and make changes, when using the Shiki plugin. When you enter the code block, to make changes, you can see, that then the default CodeMirror 6 syntax highlighting is applied. To be honest, for me, this is very annoying. I only use editing mode, and I want to be able to click inside any code block anytime to make changes. Using this approach, it would also be possible to simply use Prism.js syntax highlighting in editing mode (so the syntax highlighting would be identical), but as I said, you'd lose every benefit of the CodeMirror editor.

I would also find it cool, when both of the syntax highlighting would give the same result, but it is not my decision unfortunately.

If you find a plugin, which applies to editing mode and reading mode the same syntax highlighting, but not like this, as the Shiki plugin does, I am happy to implement it.

So unfortunately, I won't implement this approach, but as I said, I am open to alternative ways, but they'll have to work in editing mode differently than the Shiki plugin.
