### ISSUE TITLE
Toggle color picker dialog does not work under Linux (Ubuntu)

### ISSUE THREAD

**Issue by gnap114039** [mugiwara85/CodeblockCustomizer#11]
I have tried to toggle all color picker setting, but it seem nothing pop up. 
![Screenshot from 2023-05-10 16-19-11](https://github.com/mugiwara85/CodeblockCustomizer/assets/50070731/b42ff195-c655-4bb9-8b2a-bf53777d9cf8)

<br>

PC os: ubuntu 16.04 and ubuntu 22.04, both have same issue.
Obsidian version: v1.2.8
Codeblock Customizer plugin version: 1.1.7

**Comment by mugiwara85** [comment]
Did you get an error message in the console? I will look into it this week.

**Comment by mugiwara85** [comment]
Yes, but that error is something else. Not related to this problem. The plugin was tested on Windows only, so it is possible that I have to correct some small errors which arise on Linux. I will check it this week, and give you an answer (and hopefully a fix as well :) )

**Comment by mugiwara85** [comment]
This is fixed in v1.1.8

**Comment by gnap114039** [comment]
> This is fixed in v1.1.8

That's works, thx alot ~
