### ISSUE TITLE
How to change the color of the output?

### ISSUE THREAD

**Issue by merlinuwe** [mugiwara85/CodeblockCustomizer#14]
Thanks for your great plugin.

This is my code:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/328da6f9-7216-4bbe-89fa-236d3546ccfc)

It renders as so:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/6931fee9-f615-4164-b6ea-e8acd5b67b4c)

How can I change the color and background color of the output text and the color of the output background?

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/442c9e06-05af-4d6f-b090-c0fb972380cf)

I tried this:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/10ecb48b-e081-4dc9-b04f-87eeef813a04)

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/08c1ece6-0dce-488a-a9b6-9335b2d23fa3)

I also tried:

```run-python file:"Einfache Textausgabe" hl:3,5-6 ausgabe:
print("Es klappt - natürlich.")
print("Es klappt - natürlich.")
print("Es klappt - natürlich.")
print("Es klappt - natürlich.")
print("Es klappt - natürlich.")
print("Es klappt - natürlich.")
print("Es klappt - natürlich.")
print("Es klappt - natürlich.")
print("Es klappt - natürlich.")
```

The changes are ment for the _code_, not for the _output_:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/9179c746-ab75-4879-8184-6589d638637b)

Am I missing something?

**Comment by mugiwara85** [comment]
Well, yes :) You are mixing two plugins here as far as I see. My plugin doesn't have an "output". You have an additionally installed plugin which runs the code. This plugin inserts the "output" part for the code block. So, to answer your question, this second plugin had to be modified to change the color. If you tell me what this plugin is called, I can have a look at it. Maybe I can somehow set the color for that part as well, but I don't want to promise anything.

**Comment by merlinuwe** [comment]
Thanks for your fast reply.

Yes, I have installed execute code plugin.

https://github.com/twibiral/obsidian-execute-code

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/9d808521-2254-465b-bb04-282ba6fb7348)

**Comment by mugiwara85** [comment]
Ok. I'll have a look at it. Either this week, or worst case next week, and give you a feedback.

**Comment by merlinuwe** [comment]
This is what I found:

/* background-color output Python, Javascript, ... */
code.language-output  {
    background-color: #0a4554 !important;  /* teal */
}

/* background-color of text */
.stdout  {
    background-color: #d0f0c0;  /* hellgelb */
}

/* color of text */
:not(.use-custom-output-color) code.language-output span.stdout  {
    color: black !important;
    font-weight: bold !important;
}

**Comment by mugiwara85** [comment]
I looked at this problem, but unfortunately, this is not so easy to solve, if it is even possible. As I said earlier, this is a different plugin. I understand that it would be great if my plugin could also highlight lines in the output and offer the same functionality, but this just raises so many problems and questions, that I am not sure if it is feasible to solve this. I leave this ticket open, so I can think about it, but it might take a while until I have a solution.

**Comment by merlinuwe** [comment]
Thank you very much for your response. I understand. 

In the meantime one can use my own css to make it look as so:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/4bb7ddc7-e553-4a6a-aafe-a13d5880f302)

Perhaps you can put this or a similar CSS into the documentation to help others.

**Comment by mugiwara85** [comment]
What theme are you using? That Python Icon looks horrible. It should look like this:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/222d9306-ccc3-429f-bc13-5776fd4062dc)

I forgot to mention, when I tried it out, the background color was set for the output by default. Have you tried using a different theme?

**Comment by merlinuwe** [comment]
Yes, I work with Minimal theme dark mode.

**Comment by mugiwara85** [comment]
Minimal theme looks like this on my machine. 
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/8903491a-ce3c-480f-84cf-a230cc8d5818)

Did you make any other changes? Maybe custom css or something like that?
There is something wrong with the icon. Every icon has a transparent background. So it should work properly. 
You can change the color of the line numbers. It is called `Gutter text color` in the setting.

**Comment by merlinuwe** [comment]
Yes, I remember I had changed the color of the numbers. Now it is #dadada

Because of this issue I had to add some CSS:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/bf492deb-5da7-4e7e-afa9-cdde36d20ab4)

**Comment by mugiwara85** [comment]
Wow! There is something very wrong with your Obsidian :D 
The plugin definitely does not show comments like that. I am 100% sure about that. I saw that behavior however, in other plugins. Do you maybe have installed and enabled Better Codeblock or Advanced Codeblock plugins? Or any other plugins which does something with code blocks?
I would suggest to disable them one by one, and restart Obsidian every time after you disabled one. You can do that with the custom CSS as well.
Something is messing things up.

**Comment by merlinuwe** [comment]
Yes I used it, befor I knew about your plugin. ;-) But as you see, it's deactivated.

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/17f5cda9-9743-4b20-b701-2efc5c521b96)

**Comment by mugiwara85** [comment]
Hm.. but still. The comments should not look like that. I would still recommend disabling every plugin and custom CSS one by one and restarting obsidian, to see which causes this behavior. I think other people would have mentioned that already if it would cause this.

**Comment by merlinuwe** [comment]
Switched all of my 33 css-files of.

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/13fcc213-d5ec-462b-b2ea-e5a26dee3c36)

Aaaaaa...

(Good, that I noted before the ones that were off of them.)

**Comment by mugiwara85** [comment]
Looks much much better. Also note the python icon is shown as it should!

Now back to the comment. It is one line, because it has one line number. Are you sure there isn't any line break there. Or just insert a new comment.

**Comment by mugiwara85** [comment]
Try to insert a new comment to see how that is displayed

**Comment by merlinuwe** [comment]
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/3dbe9922-31da-4f20-83e0-826c558f374d)

**Comment by mugiwara85** [comment]
There is definitely something else. Did you also disable every plugin (just temporarily) and restarted obsidian?

**Comment by merlinuwe** [comment]
I have 100 of them ...

**Comment by mugiwara85** [comment]
ok :D 
You could just hit Ctrl + Shift + I hover to the comment, and maybe that way you could see what CSS is applied. That way maybe it would simpler to identify what is causing this.

**Comment by merlinuwe** [comment]
Believe it or not:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/b61ba08b-9c17-465f-8339-d42576a6eb51)

Only activating and deactivating of some plugins corrected the rendering of the comments...

**Comment by mugiwara85** [comment]
Yes! Victory!!!!!

**Comment by mugiwara85** [comment]
But you have the wrong python icon again :D

**Comment by merlinuwe** [comment]
Oh ...

**Comment by merlinuwe** [comment]
Strg-Shift-i should be my friend ...

**Comment by mugiwara85** [comment]
yepp

**Comment by mugiwara85** [comment]
are your plugins and themes up to date?

**Comment by merlinuwe** [comment]
The first thing I do every day...

**Comment by merlinuwe** [comment]
Too much information. Computer says "no"..

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/45f21a95-2d1d-429f-9aaa-d942b2aac64c)

**Comment by mugiwara85** [comment]
Click on "computed". There is a summary what is applied. Maybe it is possible to better point out the problem.

**Comment by merlinuwe** [comment]
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/68243d8a-d837-446d-813b-49ebdbd7928a)

**Comment by mugiwara85** [comment]
background color! What is setting that. If you hover to background color, a small arrow should appear. If you klick on it, it should take you the css what is setting that.

**Comment by merlinuwe** [comment]
Here it is ...

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/1d5943ca-0370-4902-9997-ff17159c8057)

**Comment by mugiwara85** [comment]
any plugin which does something with images?

**Comment by merlinuwe** [comment]
There is no arrow ....

**Comment by mugiwara85** [comment]
you already found it!

**Comment by merlinuwe** [comment]
Yes, but where is the causing css?

**Comment by mugiwara85** [comment]
> There is no arrow when I hover over this ....
> 
> ![image](https://user-images.githubusercontent.com/4138869/239709780-7fcd5307-0791-46ad-9a0a-ad8d10db1889.png)

I meant on the "computed" tab. But you already found it. Now you just have to figure out, what is causing this.

**Comment by mugiwara85** [comment]
> Yes, but where is the causing css?

This is the causing css. There is some plugin which sets for `img` the background color. Unfortunately it is not visible which plugin it is.

**Comment by merlinuwe** [comment]
This line is in none of my custom .css files ...

**Comment by mugiwara85** [comment]
then it is a plugin....

**Comment by merlinuwe** [comment]
Do you know U2?

**Comment by merlinuwe** [comment]
"But I still have it found what I was looking for..."

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/b23d003d-6816-407a-8614-85dab36e64a4)

**Comment by mugiwara85** [comment]
No problem :) Happy to help!

**Comment by mayurankv** [comment]
Hi, in regards to the original FR to do with letting highlighting work with the execute code plugin, I would vehemently argue against this aggregation.
First of all, the execute plugin can allow for live response (i.e. a prompt which can be used to input to the program) so the number of lines would not be static necessarily even in Preview mode.
Second, the execute plugin output is code OUTPUT, not source code, and as such highlighting this should have a totally different meaning to highlighting in the source code.
I can probably come up with a number of other reasons to avoid doing this (let alone the added effort and overhead) but I would suggest avoiding this.

**Comment by mugiwara85** [comment]
I have to agree on this one. It would be too complicated.
