### ISSUE TITLE
Feature Request add an option to determine whether the number of rows is displayed

### ISSUE THREAD

**Issue by Wuming-HUST** [mugiwara85/CodeblockCustomizer#19]
As the title says, add an option to the first line to control whether the code block displays line numbers.

**Comment by mugiwara85** [comment]
You mean like `ln:0` to do NOT show line numbers, and `ln:1` to show linenumbers for that specific code block?

**Comment by Wuming-HUST** [comment]
Yeah, that's what I mean.

**Comment by mugiwara85** [comment]
ok, I can do that. I am working on some bugs, so soon a new release will be available. This will then include this option as well.

**Comment by Wuming-HUST** [comment]
Thanks.

**Comment by mugiwara85** [comment]
Available in current release. Please read the updated README.

**Comment by Wuming-HUST** [comment]
Thanks for your work.
