### ISSUE TITLE
Errors in JavaScript console

### ISSUE THREAD

**Issue by mnaoumov** [mugiwara85/CodeblockCustomizer#2]
```
plugin:codeblock-customizer:2046 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at ReadingView (plugin:codeblock-customizer:2046:23)
```

**Comment by mugiwara85** [comment]
Did you use an earlier version? If yes, close obsidian, delete the data.json file, and start obsidian. If the problem still occurs you have to provide more details how and when the error occurs.

**Comment by mnaoumov** [comment]
@mugiwara85 I am currently debugging it. The issue is intermittent. Once I detect it, I will make a PR
