### ISSUE TITLE
New Fearture Needed: an alias name for hightlight color.

### ISSUE THREAD

**Issue by Syutenjyo** [mugiwara85/CodeblockCustomizer#26]
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/69134968/30207d0c-b07a-4ccd-96bf-e440857733d4)
As you can see, the name for "Alternative Highlight Colors"  is fixed while it was created. I now have to create duplicate colors for those colors which refer to same meaning.So an alias name, sometimes, can be convenient.

**Comment by mugiwara85** [comment]
I disagree. Why not consider first the name of the color and then create it? Why would you need multiple names for the same color? This feature won't be added.
