### ISSUE TITLE
Effects don't show up in reading view.

### ISSUE THREAD

**Issue by keyboard-penman** [mugiwara85/CodeblockCustomizer#29]
Hi, I just recently tried out your plugin.

Awesome plugin but it has one slight problem : Effects such as line highlighting, display of file name, display of language name and the indentation guides do not show up in the codeblock in reading mode.

**Comment by mugiwara85** [comment]
They definitely do. Just switch the documents once to refresh it.

**Comment by mayurankv** [comment]
In a future version, the only things that shouldn't show up immediately, would be changes to the codeblock parameters (e.g. which line highlights, code folding, line number offset etc.). This unfortunately is a limitation of the obsidian parser for changes which does not register changes after the language name in codeblocks as something to refresh for. See [this forum post](https://forum.obsidian.md/t/postprocessor-does-not-process-changes-after-codeblock-language/61010/4). If this is going to change, then obsidian would have to make that change so please go and like/bump that thread if you want everything to instantly update!

**Comment by mayurankv** [comment]
@mugiwara85 Maybe rename this issue to make it an issue addressing non-instant renders for codeblock parameters?

**Comment by mayurankv** [comment]
Ok, I created a separate issue for this because what I'm referring to may not be the issue that @keyboard-penman had. The meta issue is now at #32.

**Comment by mugiwara85** [comment]
It should work with the current release now as it should. Just report back, if you experience any issues.
