### ISSUE TITLE
Keep default visuals.

### ISSUE THREAD

**Issue by keyboard-penman** [mugiwara85/CodeblockCustomizer#30]
This is less of an issue report and more of a feature request.

Could it be possible to add an option to the plugin to allow the appearance of code blocks (syntax highlighting, background color, highlighted line color) to remain as they would be for that particular Obsidian theme, without the plugin's own theme being applied to codeblocks?

Thanks.

**Comment by mugiwara85** [comment]
Syntax highlighting???? I don't do anything with syntax highlighting. Please explain what you mean by this?
Background color - you can change it.
Highlighted line color - Is there a theme which can highlight lines in code blocks?
Don't really understand what you mean by this question, or what the point would be?

**Comment by mayurankv** [comment]
I actually agree that the background color should be initially set to the default theme color. I will try to make those changes to the PR #28.

@keyboard-penman do you think that the default highlighting color should be the color that obsidian uses to highlight normal text? This is doable but I'm not sure it would look pleasant in a codeblock? What are your thoughts @mugiwara85.

**Comment by mugiwara85** [comment]
> I actually agree that the background color should be initially set to the default theme color. I will try to make those changes to the PR #28.
> 
> @keyboard-penman do you think that the default highlighting color should be the color that obsidian uses to highlight normal text? This is doable but I'm not sure it would look pleasant in a codeblock? What are your thoughts @mugiwara85.

No, that color would definitely not look ok for highlighting. Background color be set to the default color of theme, but I would create a new theme for that maybe. But I don't see it as a "big problem". I can still add something similar later. Right now the PR is more important, because without it, I can't release the other fixes neither :)

**Comment by mugiwara85** [comment]
The default theme is Obsidian now. Please also read the README.
