### ISSUE TITLE
Can't collapse last block on note

### ISSUE THREAD

**Issue by dm7500** [mugiwara85/CodeblockCustomizer#35]
If I have a note with multiple blocks, the final block on the page can never be collapsed. I've tried this with up to 5 blocks, with the same issue. Has anyone sen something similar?

**Comment by mugiwara85** [comment]
That's definitely an issue on your end. It does work for me. I have notes with more than 100 blocks. Please create a new vault an try there. If it does work there, then probably some conflict, with another plugin or custom css or theme. You need to narrow it down, what causes this, and then I can have a look at it if I can reproduce.

**Comment by mugiwara85** [comment]
I am closing this, since I haven't heard back from you. If the problem still persists, just get back to me.
