### ISSUE TITLE
How to remove gutter gap in reading view?

### ISSUE THREAD

**Issue by helicos6** [mugiwara85/CodeblockCustomizer#36]
@mugiwara85 Thank you for creating this excellent plug-in. I discovered it just yesterday and find it very useful.

One small visual quirk I would like to change are the gutter gaps in reading view, as shown here:

![2023-06-25_18-36-47](https://github.com/mugiwara85/CodeblockCustomizer/assets/34452093/dc4a899d-70d2-4ac3-9299-728220a60c2f)

These gutter gaps are not present in the editing view, and I think it looks much nicer:

![2023-06-25_18-36-22](https://github.com/mugiwara85/CodeblockCustomizer/assets/34452093/8bc9e3ef-8492-4869-8a04-4235daf737f8)

Can you please tell me how I can make the reading view look the same as the editing view for the gutter?

**Comment by mayurankv** [comment]
Hi @helicos6, just to let you know this has been addressed and is scheduled to be fixed in the upcoming release!

**Comment by helicos6** [comment]
@mayurankv Thank you. 🙂

**Comment by mugiwara85** [comment]
@helicos6 As mayurankv said, in the next release this will be fixed. Unfortunately the release is delayed a little, because the plugin is undergoing major changes (from the point of how and which CSS classes are used). The next release will also include some smaller new features.

**Comment by helicos6** [comment]
@mugiwara85 Thank you, looking forward to the update. 😃

**Comment by mugiwara85** [comment]
It should be fixed now. Should there be any problem, please get back to me.
