### ISSUE TITLE
Code block in nested lists can't display the header

### ISSUE THREAD

**Issue by hanekit** [mugiwara85/CodeblockCustomizer#37]
@mugiwara85 Thank you for creating this beautiful and useful plug-in.

I have found in use that when placing a code block in a list (both ordered and unordered) , which means that each line of the code block is preceded by an tab/indent), the header with code language doesn't show up anymore.

Here is my test code:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/84430289/622d0c53-0ffc-4024-bb0a-67baf5354440)

Here is how it renders in code/edit/read view:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/84430289/310be486-e96f-4f6c-a6af-21b7e1912900)

All tests were conducted in sandbox mode without any interruptions，
with both the "Always display codeblock language" switch in on/off mode.

I hope this issue can be resolved，
because the code blocks in the list are often used when recording steps.

Thank you for your reading.

---

Obsidian: v1.3.5
Codeblock Customizer: v1.1.9

**Comment by mugiwara85** [comment]
Hi! Yes, someone already told me this in another issue. I will fix this also in the next release (that's why the release takes a little longer than usual).

**Comment by hanekit** [comment]
@mugiwara85 Thank you vary much, waiting for your nice job 😊!
