### ISSUE TITLE
[bug]: when I embedded a codeblock, the line number will cover the content

### ISSUE THREAD

**Issue by doit132** [mugiwara85/CodeblockCustomizer#39]
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/6d178536-54c9-4743-bd6e-b59b264a5d78)

**Comment by mugiwara85** [comment]
dumb question, but how did you do that? Can you send me the source?

**Comment by mugiwara85** [comment]
Oh, I know now. I will fix it tomorrow.

**Comment by mugiwara85** [comment]
Sorry, it took this long, but it is fixed now in release 1.2.1. It should work now correctly.
