### ISSUE TITLE
Notes with Code blocks no longer loading

### ISSUE THREAD

**Issue by helicos6** [mugiwara85/CodeblockCustomizer#40]
I just updated this plug-in and now Obsidian can't open any notes with meta data.

Shows me this notice:

<img width="245" alt="image" src="https://github.com/mugiwara85/CodeblockCustomizer/assets/34452093/5e6531b4-40ed-498a-bd92-b72a913d923a">

<br>
<br>
All other plugins have been disabled, so I can confirm it's this plugin.

**Comment by helicos6** [comment]
Seems the issue is not isolated to notes with headers.

I am not able to load any notes that have code blocks.


<img width="292" alt="image" src="https://github.com/mugiwara85/CodeblockCustomizer/assets/34452093/745bbe12-6d1d-4274-be7e-679bb6e7e487">

**Comment by mugiwara85** [comment]
Did you remove the data.json file? I specifically wrote it in the README. Reinstalling the plugin should also solve the problem.

**Comment by helicos6** [comment]
Apologies. That fixed the issue.
