### ISSUE TITLE
Since last update: cannot read properties of undefined (reading 'header')

### ISSUE THREAD

**Issue by merlinuwe** [mugiwara85/CodeblockCustomizer#41]
Problems with code.

Since the update, I got in some of my notes this error message:

cannot read properties of undefined (reading 'header')

If I deactivate the plugin, everything runs fine.

Windows 10, latest Obsidian, latest CodeblockCustomizer plugin from yesterday.

**Comment by mugiwara85** [comment]
Did you remove the data.json file, or reinstalled the plugin as written in the readme?

**Comment by merlinuwe** [comment]
Thanks for your very fast reply. Yes, after I have read your text in the plugin information. ;-)

(Isn't it possible to delete this file automatically in the update procedure?)

**Comment by mugiwara85** [comment]
Is it working now?
Not that I know of (which doesn't mean it is not possible, only that I haven't found a way for now.). This file contains the settings, and since I remade the settings (because I messed up a few things) it was required to delete the file. In the future there won't be any issue regarding this.

**Comment by merlinuwe** [comment]
It does not seem to format the code. (I deactivated my own .css.)

This code

```python file:"Uhrzeit ausgeben" hl:3 unfold
# Hier ist ein einfaches Python-Skript, das die aktuelle Uhrzeit ausgibt:
import datetime
# This is the second comment
now = datetime.datetime.now()
print("Aktuelle Uhrzeit:", now.strftime("%H:%M:%S"))
```

```powershell
$attachmentsDirectory = "c:\versuch"
Write-Host "lalala"
#Ausgabe einer Meldung, wenn das Verzeichnis attachments nicht vorhanden ist
Write-Output "INFO: Das Verzeichnis $attachmentsDirectory wurde nicht gefunden."
```

Shows in edit mode as

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/ed405e65-f16d-4f4c-b937-8c3d8b1cfb5d)


Shows in view mode as

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/9dc2dc5a-edd2-4f89-a4c4-0204bc928cd5)

but not similar to

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/c3f47648-8a1a-4bf0-a68c-fb8be35eceb7)

**Comment by mugiwara85** [comment]
You have the default Obsidian theme selected. Did you read the readme?

That's how it looks on my machine.

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/74873f93-18ba-4660-a9d5-edb5fda33420)
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/59d26deb-3b28-40a6-8d37-ebdf7b61ce50)

**Comment by merlinuwe** [comment]
Yes, I use the default theme.

I have activated my css snippet

```
/* Lösung für den Edit- und den Ansichts-Modus */

.comment  {
display: contents;

}

/* Behebt das Problem mit dem lime Balken im codeblock */
/* Spielt aber in Python itertools.md immer noch verrückt, wenn man die Headline 2 Inhaltsverzeichnis minimiert > */

body > div.app-container > div.horizontal-main-container > div > div.workspace-split.mod-vertical.mod-root > div > div.workspace-tab-container > div > div > div.view-content > div.markdown-reading-view > div > div > div:nth-child(10) > pre > pre  {
    background-color: #0b2b35 !important;
    
}


/* Code im dark theme 
.theme-dark code  {
    background-color: #002b36 !important;
    font-size: 0.3em;
    
}
*/

/* Ändert die Schriftgröße von mehrzeiligem Code, der durch ein Plugin beeinflusst wird. */
.theme-dark .codeblock-customizer-RVline-text  {
    font-size: 1.3em;
    color: lightyellow;
    background-color: #073642;  /* teal */
}

.theme-light .codeblock-customizer-RVline-text  {
    font-size: 1.3em;
    color: black;
    background-color: #c3c3c3;  /* hellgrau */
}
```

and the probleme with the line break is gone.

**Comment by mugiwara85** [comment]
The class `codeblock-customizer-RVline-text` does not exist anymore. 
But you had the same problem last time as well. You definitely have some conflict with something on your machine.

**Comment by merlinuwe** [comment]
Now I deactivated the classes codeblock-customizer-RVline-text in my custom css.

I remember ...

When I format the code like this, everything is ok? ;-)

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/37f019af-4bff-4d4f-96e7-1f732318dd5a)

**Comment by mugiwara85** [comment]
They are in the plugin. Selected the solarized theme.

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/02fb1ec3-a7d6-423f-933c-d9ff9a62f107)

**Comment by merlinuwe** [comment]
In the moment, I did it right - it suddenly works ... Thank you very much for your great plugin and the fast help!

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/4138869/f5094ff7-08b5-4425-929d-8ec2ebfa54a8)

**Comment by mugiwara85** [comment]
Anytime :)
