### ISSUE TITLE
[bug]: Cannot open note with the plug-in on

### ISSUE THREAD

**Issue by jiywww** [mugiwara85/CodeblockCustomizer#42]
Error:
Failed to load "Daily Notes/2023-08-12.md" Cannot read properties of undefined (reading 'header')

Can be fixed by turn off the Codeblock Customizer plug-in.

**Comment by mugiwara85** [comment]
Either remove the data.json file, or reinstall the plugin as written in the README. After that it should work as expected. Sorry, but this must be done only once.

**Comment by jiywww** [comment]
> Either remove the data.json file, or reinstall the plugin as written in the README. After that it should work as expected. Sorry, but this must be done only once. Also please re-read the README because there are some important changes there.

This resolved my issue. Sorry I did not check on the README file before post the issue.
