### ISSUE TITLE
[Feature Request] When the cursor is in the code block, I hope the copy button still exists

### ISSUE THREAD

**Issue by doit132** [mugiwara85/CodeblockCustomizer#46]
# Current Situation

When I click inside the code block, which means placing the cursor inside the code block, the copy button for the code block disappears, making it impossible to copy

Only by placing the cursor outside the code block will the copy button be displayed for copying

# Animation demonstration

![动画](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/259a5a9c-9710-49e9-97ef-3087796ac1ee)

**Comment by mugiwara85** [comment]
That is the default behavior of the default copy button of Obsidian. I can add an option to display a copy button just like the "delete code" button, if that helps. Would that be ok?

**Comment by doit132** [comment]
> That is the default behavior of the default copy button of Obsidian. I can add an option to display a copy button just like the "delete code" button, if that helps. Would that be ok?↳

That's also a good idea

**Comment by mugiwara85** [comment]
Added an option in version 1.2.2 to display a copy code button. This is very similar to the original Obsidian one, but it will be displayed always. If there is any problem, just reply here.
