### ISSUE TITLE
[Bug] When inputting content in Chinese at the head of a code block, it can cause some problems

### ISSUE THREAD

**Issue by doit132** [mugiwara85/CodeblockCustomizer#47]
# Problem Description

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/705a4a7b-83f7-41be-87af-2cc70146646a)

When I input content in the header of the code block using Chinese input method, there will be a space like thing in front of Chinese

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/c8edcdec-baf4-4293-9ea6-7707c8b1ff5c)

# Animation demonstration

![动画](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/5da47ba5-0595-4077-aa62-69c1a7ef790c)

This problem not only occurs when inputting Chinese, but also when using the Chinese input method, regardless of whether the final screen is in English or Chinese

# testing environment

- obsidian v1.4.5 or previous version
- obsidian sandbox vault

**Comment by mugiwara85** [comment]
That's interesting. I think it might have to do something with the input method, because if you take a chines string, then it wil be displayed correctly:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/d6e5ebc0-ef20-4d0b-9425-9f3a1c017397)

Can you remove that first character?
I can look into this problem as well.

**Comment by mugiwara85** [comment]
Also, can you please try it out if the same happens if you disable the plugin?

**Comment by doit132** [comment]
> That's interesting. I think it might have to do something with the input method, because if you take a chines string, then it wil be displayed correctly: ![image](https://user-images.githubusercontent.com/65603765/264992760-d6e5ebc0-ef20-4d0b-9425-9f3a1c017397.png)
> 
> 这很有趣。我认为它可能必须对输入法做一些事情，因为如果你拿一个中文字符串，那么它就会正确显示：
> 
> Can you remove that first character? I can look into this problem as well.↳

There is no problem with the display of Chinese characters, but this space may be added during input, and may cause the entire page rendering to fail

**Comment by mugiwara85** [comment]
hm. interesting, as I don't do anything that could cause this. it should be just simply text. but I believe you. I will look into it what can cause this. I might get back to you if I have any questions.

**Comment by doit132** [comment]
Recently, the input method I used has been updated and this issue no longer occurs

**Comment by mugiwara85** [comment]
If the update of the input method fixed this, then this means for me, that the input method you use causes these issues. There are some cases when the lines loose the associated classes. For example if you have a codeblock with no text, and collapse and uncollapse it, then somtimes it can be observed that not all the lines after uncollapse gets the classes associated with them which they should have. I think however, that this is either an Obsidian or a CodeMirror bug. I leaves this issue open for now, but it could take some time to figure this out.
