### ISSUE TITLE
[Bug] When the cursor clicks inside the code block and then outside the code block, the entire document jumps up

### ISSUE THREAD

**Issue by doit132** [mugiwara85/CodeblockCustomizer#48]
# Animation demonstration
![动画](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/c05d67ee-4f90-42ef-bc40-5dd4bd61c192)

**Comment by mugiwara85** [comment]
I can't reproduce this unfortunately. Can you send me maybe a sample document?

**Comment by doit132** [comment]
> I can't reproduce this unfortunately. Can you send me maybe a sample document?↳

The key point is that the code block is located in the upper part of the visible area of the document. 

If the code block is located in the middle or below the visible area, it will not cause jumping

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/c092d6f6-17ab-4f1e-9c2d-71dd6325019d)

**Comment by mugiwara85** [comment]
I think that bug is coming from Obsidian. If I disable the plugin, the same behavior occurs. Can you verify that?

**Comment by doit132** [comment]
> I think that bug is coming from Obsidian. If I disable the plugin, the same behavior occurs. Can you verify that?↳

Yes, I just realized this, but if I close the plugin in another library, it won't jump

**Comment by mugiwara85** [comment]
What do you mean by "if I close the plugin in another library, it won't jump"

**Comment by mugiwara85** [comment]
If I disable the plugin and set the "Properties in document" to source, I still have that jumping. Correct me if I am wrong, but this seems to me as an Obsidian bug.

**Comment by doit132** [comment]
> If I disable the plugin and set the "Properties in document" to source, I still have that jumping. Correct me if I am wrong, but this seems to me as an Obsidian bug.↳

If property is set to visible and plugin is turned on, there will definitely be jumping phenomenon
If property is set to visible and plugin is turned off, there may not be any jumping phenomenon
If property is set to source and plugin is opened, there will definitely be jumping phenomenon
If property is set to source and plugin is turned off, there will be no jumping phenomenon

**Comment by mugiwara85** [comment]
I am confused a little as well. This with the property set to source, and plugin turned off:

https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/0c47f44b-0a2d-4f27-b4c3-16e73ec65bee

**Comment by mugiwara85** [comment]
I just checked again, and this issue seems to be solved now. Maybe it was an Obsidian bug. Could you confirm it?

**Comment by mugiwara85** [comment]
no reply received

**Comment by doit132** [comment]
> no reply received 未收到答复

I found that this may have been caused by me modifying the font size in the code block

```
.cm-s-obsidian .HyperMD-codeblock {
  font-size: 0.7em;
}
```

Even in the latest version, if I enable the CSS style above, this phenomenon will still occur, So I turned off this style setting

**Comment by mugiwara85** [comment]
That's interesting, because I could reproduce the issue, but I didn't modify the font size of the code blocks. I will look at it again.
