### ISSUE TITLE
[Question] Is there a way to make double chains work in code blocks

### ISSUE THREAD

**Issue by doit132** [mugiwara85/CodeblockCustomizer#49]

**Comment by mugiwara85** [comment]
What are double chains?

**Comment by doit132** [comment]
> What are double chains?↳

double chains is [[file_name]]

**Comment by mugiwara85** [comment]
Sorry, I am not following. Can you explain it a little bit more in detail what would you like?

**Comment by doit132** [comment]
> Sorry, I am not following. Can you explain it a little bit more in detail what would you like?

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/527e0e32-1731-4277-bd42-21e61f10cb81)

Is there a way to make it clickable in the code block

**Comment by mugiwara85** [comment]
aaa ok, now I get it. You mean a link. Probably yes, but the question is, if there is a programming language which could contain such a syntax? Because if yes, then that would mean that they would be converted to links. I'll look into this as well.

**Comment by mugiwara85** [comment]
Just a heads up! Links will be available in the next release. I have it almost ready, just have to fix a few problems in reading mode.

**Comment by mugiwara85** [comment]
Available in version 1.2.4. Please test it, and report back if there is any problem.
