### ISSUE TITLE
This plugin does not seem to be searchable in Obsidian

### ISSUE THREAD

**Issue by GabrielWF** [mugiwara85/CodeblockCustomizer#5]
It looks like this plugin is currently not available on the Obsidian Community Plugin Marketplace. Is it not released yet?
![market](https://user-images.githubusercontent.com/78136563/232206222-63089f95-bcb4-4e70-b4e9-0e4c3f369bf5.png)

I was troubled by Obsidian's code block optimization for a long time, and your plugin helped me a lot. I hope you have noticed this issue to make sure your plugin is known to more people.

**Comment by mugiwara85** [comment]
Hi!

Thanks for the feedback! If you have an idea or requirement or found a bug just post it. If it is something others could also benefit from, I will implement it. 
I have submitted the plugin for release at 26th January. Here is the pull request: https://github.com/obsidianmd/obsidian-releases/pull/1579
Unfortunately it takes for the Obsidian team a very long time to release plugins nowadays. But hopefully it will get released soon :)

**Comment by mugiwara85** [comment]
The plugin is finally released! Now it is possible to search and install it directly from Obsidian.
