### ISSUE TITLE
feature request: Indent before the code block

### ISSUE THREAD

**Issue by avraam-inside** [mugiwara85/CodeblockCustomizer#52]
There is a known problem in obsidian - this is the design of code blocks inside lists in live preview:
https://forum.obsidian.md/t/live-preview-better-support-of-code-blocks-in-lists/31352/57

Unfortunately, the authors have been dealing with the problem for almost 2 years and without result.

At the same time, you have a wonderful extension that greatly improves the user experience!

If you could add indents in front of your code blocks in the extension, it would be wonderful!

Thanks!

**Comment by mugiwara85** [comment]
You mean when a codeblock is inside a list? You mean the red vertical line I drew in with red (between 1 and 2)?
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/647fd28b-86ff-4d63-9177-b4d8b8d002bc)

**Comment by avraam-inside** [comment]
I mean the need for indentation before the code block in some cases (for example, inside the list)

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/52919010/5d774645-cfa4-4391-8238-afd278448a08)

**Comment by mugiwara85** [comment]
ah sorry. You mean indentation. I was thinking about indentation lines. Sorry, my bad. 
But I am still confused a little. On the picture the  codeblock is indented, or not? Maybe we are not talking about the same thing. Could you send two pictures. One where it is wrong, and one where I can see what you need?

**Comment by avraam-inside** [comment]
Of course: 
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/52919010/6720aa23-a80b-46bb-8860-abbd2bc82ded)

**Comment by mugiwara85** [comment]
In reading mode it should work.
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/26bd314a-a6f7-4017-8428-71525514a072)

In edit mode it doesn't. I didn't even notice that. I will look into this

**Comment by mugiwara85** [comment]
can you name other cases when the code block needs to be intended? You said, inside a list, but what are the other cases?

**Comment by avraam-inside** [comment]
Here are the cases that come to mind:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/52919010/d2d01184-ff78-4db1-8711-5ef19d7ded85)

If possible, you could set the left indent depending on the number of spaces before the first set of ``` or set it to the option after (example): ```css indent:4

**Comment by mugiwara85** [comment]
thank you! I might have an idea how to solve this. I try to solve it until the next release.

**Comment by mugiwara85** [comment]
Just a quick question. This way would it be ok?
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/6768fcfe-d24b-4d74-a7c8-15034b12b38d)

**Comment by mugiwara85** [comment]
It's not perfect, because the indentation lines are missing, but I didn't find another way to solve this reliably.

**Comment by mugiwara85** [comment]
Available in version 1.2.4. Please test it, and if there is any problem, just report back.
