### ISSUE TITLE
[Bug] When I enable the show copy code button function, it can only copy a portion of long code

### ISSUE THREAD

**Issue by doit132** [mugiwara85/CodeblockCustomizer#53]
# enable the show copy code button function

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/2c81c6be-5fd2-449b-8a00-036481628192)

### Demo Video

![动画-tuya](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/286104cb-7d73-410c-b602-adb56cd9cbfc)

- There are a total of 40 lines of code in the code block, but only 35 lines have been copied out

# disable the show copy code button function

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/3a5e457b-5442-466c-a5da-6eba7993048c)

### Demo Video

![动画-tuya](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/346de0d9-070d-4d11-9ee7-6fe3a2bee544)

**Comment by mugiwara85** [comment]
Oh, that's interesting. I will look into it.

**Comment by mugiwara85** [comment]
Do you know, if this behavior is also true for the delete code button?

**Comment by mugiwara85** [comment]
It is fixed in version 1.2.4. Should there be any problem, just report back.
