### ISSUE TITLE
[Bug] When inputting Chinese, the link disappears

### ISSUE THREAD

**Issue by doit132** [mugiwara85/CodeblockCustomizer#57]
# Link does not disappear

I am using C language without annotations

### Animation demonstration

![动画](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/a38ba181-bbd3-44a2-a9ed-5a6bc275d8e0)

# Link disappear

I am using C language with annotations

### Animation demonstration

![动画](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/48139aaa-1e14-497b-a3cf-aba923538674)

**Comment by mugiwara85** [comment]
Send me the whole text the code block contains

**Comment by doit132** [comment]
> Send me the whole text the code block contains


## I’m interested in Obsidian

First of all, tell me `bit a`bout wha `ote-taking ` fds
wha `ote-taking ` fdsfds `fsd` 
-> [[No prior experience|I have no prior experience]] ff分



---

## Official Help Site

```c
输入 [[From standard note-taking]] 输入
```



## What is this place?

This is a sandbox vault in which you can test various functionality of Obsidian. 

> [!Warning]  
> Your changes will not be saved, so please don't take actual notes in this vault.

> [!Note] Beta vault - contributions are welcome!  
> This sandbox vault is in beta!
> 
> If you spot a typo or a mistake, feel free to submit a pull request [here](https://github.com/obsidianmd/obsidian-docs/tree/master/Sandbox) .



```c
fjdkjfk

```

**Comment by mugiwara85** [comment]
I am pretty sure, that this has something to do with your input method as last time, because it works for me:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/250afa2e-4834-433a-b3a7-7bc046e057a2)

How are you inputting chineese text? Are you on Windows? Did you add a chineese keyboard layout? Are you using a software for that? Or how?
Provide details so I can reproduce the issue.

**Comment by doit132** [comment]
you should add //，please refer https://github.com/mugiwara85/CodeblockCustomizer/issues/57#issue-1918639663

**Comment by mugiwara85** [comment]
I did. Still works:

![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/9acb1c58-2854-450a-acb5-7bacfb52ab91)

**Comment by doit132** [comment]
This is too strange. I have changed multiple Chinese input methods and killed all software backends that may affect input behavior, but there is still a phenomenon of link disappearance

Here is the test library I am using
[Obsidian Sandbox.zip](https://github.com/mugiwara85/CodeblockCustomizer/files/12763051/Obsidian.Sandbox.zip)

I am using a Windows system, The version number is 22H2

**Comment by mugiwara85** [comment]
Hmm, interesting. I opened the Sandbox you sent, but it is still displayed correctly:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/2b4a78e2-0170-44d0-98a0-b3e88ab90762)

**Comment by doit132** [comment]
If I enter English after the link, it will not disappear. Once I enter Chinese after the link and go to the screen, the link will disappear

**Comment by mugiwara85** [comment]
but you enter Chinese with your input method, right? If you copy somewhere chinese text, and paste it, then it will work probably. That's why I say it has to do something with you input method.

**Comment by mugiwara85** [comment]
Can you send maybe the html of that line? Maybe we can see there, what's happening

**Comment by doit132** [comment]
> Can you send maybe the html of that line? Maybe we can see there, what's happening 你能把这行的 html 发给我吗？也许我们能看到那里发生了什么

how to get html

**Comment by mugiwara85** [comment]
press CTRL+Shift+I and navigate to that line

**Comment by doit132** [comment]
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/dc0ad092-76a8-43fd-abf7-967b70def893)

**Comment by mugiwara85** [comment]
yes, that one, but copy it and paste it here.

**Comment by doit132** [comment]
<div class="codeblock-customizer-line cm-active HyperMD-codeblock HyperMD-codeblock-bg cm-line" codeblockid="1" style=""><span class="codeblock-customizer-line-number" contenteditable="false"><span class="codeblock-customizer-line-number-element">1</span></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-hmd-codeblock" spellcheck="false">// 输入 <img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><a class="cm-hmd-internal-link" contenteditable="false"><span class="cm-underline" data-path="From standard note-taking">From standard note-taking</span></a><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"> </span></div>

**Comment by doit132** [comment]
It may really be an input method issue, and I tested several input methods and found that one of them did not cause this problem

**Comment by mugiwara85** [comment]
It probably is. If you give me a link for one of your input method software then I can download it, and have a look at it.

**Comment by doit132** [comment]
https://github.com/rime/weasel/releases/tag/0.15.0
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/117004316/198b887b-da15-4a9b-9a7a-2d03033b4671)

**Comment by doit132** [comment]
Now I have changed input method to sogou, this question is no longed appear
