### ISSUE TITLE
Makefile is not supported

### ISSUE THREAD

**Issue by WX-Yang** [mugiwara85/CodeblockCustomizer#61]
Unsupported programming languages don't show header, very weird !

**Comment by mugiwara85** [comment]
You'll have to explain that a little more detailed. Makefile does show the header:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/a0bced29-e053-4927-8142-dcf3b6b3d97c)

And what do you mean by that Makefile is not supported?

**Comment by mugiwara85** [comment]
did not receive any reply
