### ISSUE TITLE
Version 1.2.5 breaks Obsidian 1.4.13 and 1.4.16

### ISSUE THREAD

**Issue by reinerblock** [mugiwara85/CodeblockCustomizer#64]
Since updating Obsidian to version 1.4.13 and then 1.4.16 Obsidian stops loading plugins and shows the following:

![grafik](https://github.com/mugiwara85/CodeblockCustomizer/assets/5745579/52e3f9e2-1e44-42da-ae4c-7c225e98eadc)

I deactivated all my plugins and activated them one by one and restarted Obsidian each time. As I reached Codeblock Customizer the error occurred again.

Now I've activated all installed plugins, but Codeblock Customizer and Obsidian works fine again.

Another error that occurs is when activated notes can't be opened. Obsidian opens a tab, but the tab is empty.

**Comment by mugiwara85** [comment]
See here: https://github.com/mugiwara85/CodeblockCustomizer/issues/60

**Comment by reinerblock** [comment]
Thanks! That was the problem over here, too. After deleting data.json all works fine now. :)
