### ISSUE TITLE
Cannot read properties of undefined (reading 'common')

### ISSUE THREAD

**Issue by uxbbjozsif4515** [mugiwara85/CodeblockCustomizer#66]
In the latest version of the software, there is a plugin that causes the error "Cannot read properties of undefined (reading 'common')" when creating new text files.

**Comment by mugiwara85** [comment]
See here: https://github.com/mugiwara85/CodeblockCustomizer/issues/60

**Comment by uxbbjozsif4515** [comment]
Thank you!
