### ISSUE TITLE
Features suggestions

### ISSUE THREAD

**Issue by zzzzz-attachment** [mugiwara85/CodeblockCustomizer#70]
1. Like instead of highlighting the line  i want to highlight some part of code

suppose  on line 7
python3 blah blah blah important blah blah

i want to highlight the word important only.

2. Just like we can change colour of inline code. like that i am expecting to change codeblocks colour as well.

**Comment by mugiwara85** [comment]
1. I was already considering to offer this option. I will include this in the next release.
2. I don't really know what you mean by this? You can change the background color of code blocks. Or which color do you mean? Please explain in more detail.

**Comment by mugiwara85** [comment]
Available in current release (1.2.6). Should there be any problems please report back.
