### ISSUE TITLE
Version 1.25 still conflicts with the tasks plugin.

### ISSUE THREAD

**Issue by bing198619** [mugiwara85/CodeblockCustomizer#71]
When tasks is below version 5.0, it can be used normally with this plugin.
However, after upgrading tasks to version 5.0 or above, when there is query code for tasks on the page, after I create a new task on the page, the query code for this task will be reloaded and executed.
At first, I thought it was a problem with the tasks plugin, but after disabling this plugin, this situation disappeared.
The code of the same dataview class will not have such a problem.
The query code for tasks is similar to the following style：
```
tasks
not done
(has happens date) OR (tags includes #tracking) OR (status.type is IN_PROGRESS) 
sort by urgency
sort by done reverse
sort by created reverse
sort by status.type
group by status.type
sort by path
```

**Comment by mugiwara85** [comment]
I don't know the tasks plugin. Can you provide steps to reproduce the issue?
