### ISSUE TITLE
Conflict with Minimal theme: indentation of code blocks does not work properly in LP mode

### ISSUE THREAD

**Issue by bcdax110** [mugiwara85/CodeblockCustomizer#74]
After switch to the theme Minimal, Indentation of code blocks does not work properly in LP mode.
If there is a tab before the block, the block will "fly" to the left side of the screen.
Below is the effect of installing only the "Minimal" theme and "CodeblockCustomizer" plugin in Obsidian Sandbox.

- version info: These are the latest versions.
    - Obsidian: 1.5.3
    - Minimal theme: 7.4.8
    - CodeblockCustomizer plugin: 1.2.5

### Markdown source 
![Clip_2024-02-18_20-58-42](https://github.com/mugiwara85/CodeblockCustomizer/assets/15951421/60dc895b-a036-4b86-9273-c9b09f5e4f99)
### LP mode result:
![Clip_2024-02-18_20-53-46](https://github.com/mugiwara85/CodeblockCustomizer/assets/15951421/5b3a9c4e-c6d5-4cbd-ad05-8edaa7b68392)

### Markdown source 
![Clip_2024-02-18_20-58-28](https://github.com/mugiwara85/CodeblockCustomizer/assets/15951421/5a41b940-87dd-4048-9175-27624bd2bf67)
### LP mode result **(not work properly)**:
![Clip_2024-02-18_20-53-22](https://github.com/mugiwara85/CodeblockCustomizer/assets/15951421/63671860-d79b-4e50-b215-32a30a4653e6)

**Comment by mugiwara85** [comment]
Yeah, I also just saw, that something is not correct with the current version of Obsidian regarding the indentation. I am already working on it. Next release will fix it (hopefully, if I am done with it until then :) ).

**Comment by mugiwara85** [comment]
Fixed in current release (1.2.6). Should there be any problems please report back.
