### ISSUE TITLE
[Bug]The line of code cannot be folded in simi-fold. 

### ISSUE THREAD

**Issue by itangqiao** [mugiwara85/CodeblockCustomizer#75]
<img width="1135" alt="image" src="https://github.com/mugiwara85/CodeblockCustomizer/assets/44393379/c78f08d6-0d37-4ca3-ad5f-c39df207a145">
<img width="778" alt="image" src="https://github.com/mugiwara85/CodeblockCustomizer/assets/44393379/2ddee72d-1e3e-40e2-bded-a6598f4ee063">

**Comment by mugiwara85** [comment]
From a half sentence I don't know what you mean. Please explain in more detail the problem. The header is not even present.

**Comment by mugiwara85** [comment]
Did you specify the file parameter? For semi-folding to work, the header needs to be present, since otherwise you would not be able to fold or unfold the code block.

**Comment by itangqiao** [comment]
> Did you specify the file parameter? For semi-folding to work, the header needs to be present, since otherwise you would not be able to fold or unfold the code block.你指定了文件参数吗？为了使半折叠工作，需要存在标题，否则您将无法折叠或展开代码块。

Got it. Thank you for your help！
