### ISSUE TITLE
FeatureRequest - change colour of text inside code block

### ISSUE THREAD

**Issue by hackerman-Dan** [mugiwara85/CodeblockCustomizer#76]
It would be nice to be able to change the colour of the text inside the codeblock - to overwrite syntax highlighting if desired

I want to use code blocks in some cases for copy+pasting only and want a specific colour of the text

Unless there is something I'm missing in the settings that it can be done already

**Comment by hackerman-Dan** [comment]
Exactly! yeah like in previous note tools, I like to use light green for text with commands to paste into console. 
I would like to have a code block that then just the text is green

**Comment by mugiwara85** [comment]
ok, I just didn't know if you wanted specific lines or the whole text in the code block. But the whole text is easier to implement :) I will look into it, because I am not sure what happens if you define colors for a language, which applies syntax highlighting. I look into, and get back to you.

**Comment by hackerman-Dan** [comment]
hey @mugiwara85, do you think this is possible?

**Comment by mugiwara85** [comment]
Yes, I think, it will work. I will start to work on it at this weekend.

**Comment by hackerman-Dan** [comment]
hey man, any progress on this one?

**Comment by mugiwara85** [comment]
Yeah, I am working on it. I think it will be ready on the weekend in worst case

**Comment by mugiwara85** [comment]
hi, I just pushed it. It is not yet released, but you can just take the main.js file, and overwrite yours with it. In the "Language specific colors" tab you can now select "codeblock textcolor" and set a color. However, I just realized, that there is no way to set the colors for code blocks without a language specified. I have to add that as well.

**Comment by hackerman-Dan** [comment]
I really like it thank you!
Is there a way for the colours to also show when in editing mode? I only see it applying in reading mode

**Comment by mugiwara85** [comment]
Hmm. It should apply to editing view as well.
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/fc1b13a0-9a57-45d4-9b50-e4db85a8ae18)
Could you check in the console please, if you get any errors?

**Comment by hackerman-Dan** [comment]
weird I dont see any errors in the console
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/106969204/faf7eec2-db3d-4896-8ff2-1e428bff3ffa)

and then when I switch to reading mode:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/106969204/5e3ed32e-4e33-4ceb-9096-3f95047edca8)

**Comment by mugiwara85** [comment]
That's interesting.
It works on my machine 
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/44cbf184-ec80-4772-b8b5-f642038555ff)
Could you send me your data.json file from your vault folder inside the plugins folder?

**Comment by hackerman-Dan** [comment]
[data.json](https://github.com/mugiwara85/CodeblockCustomizer/files/14803155/data.json)
thanks for taking a look

**Comment by mugiwara85** [comment]
yeah, no problem. That's why I wanted you to test it.
But interestingly it is still green on my machine:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/4086f54f-ebf0-47d1-9341-4b596085b1a8)

Could you please check in the inspector, if you select one line, which should be colored, and then check if the marked style is applied to cm-hmd-codeblock? Or if it is even applied at all? Probably not, and that's the problem. The question is why? The line should have the class codeblock-customizer-languageSpecific-credential (credential or run, or what language you specified)
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/67160db4-36da-4796-8d64-f256f96463fe)

**Comment by hackerman-Dan** [comment]
huh yeah its crossed out in the source view weird
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/106969204/3de055c1-2986-4b7d-bb67-a42812fe7ec1)

and then if i look in the reading view, its not crossed out 
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/106969204/85bd5ff2-565e-4019-b6ac-b97a8c15d6fc)

**Comment by mugiwara85** [comment]
ah ok. So it is applied, but something overwrites it. What Obsidian Theme are you using? Maybe that causes the problem.

**Comment by hackerman-Dan** [comment]
ah yeah I am using the Atom theme, if I change to default it works perfectly :(

**Comment by mugiwara85** [comment]
No, don't worry. I just have to add the !important flag, and then it will work :). I push it in a few seconds

**Comment by mugiwara85** [comment]
I pushed it. Take the main.js, and it should work now, but please give a feedback :)

**Comment by hackerman-Dan** [comment]
wohoo it works! you're an absolute legend

**Comment by mugiwara85** [comment]
Glad I could help :)
