### ISSUE TITLE
[Feature Request] Excludes all the admonitions codeblock by default

### ISSUE THREAD

**Issue by emisjerry** [mugiwara85/CodeblockCustomizer#8]
There're many Admonitions codeblock in notes. Could they excluded by default?
ad-note, ad-info, etc. It will be better if we can specify like ad-* (wildcard) syntax.

For example:

````
```ad-note
Something new
```
````

**Comment by mugiwara85** [comment]
You can exclude them in the settings, but I will make them default. I will also implement the wildcard method next week.

**Comment by mugiwara85** [comment]
It is fixed in version 1.1.7. See release notes
