### ISSUE TITLE
Export to PDF, the code block is not expanded

### ISSUE THREAD

**Issue by imingz** [mugiwara85/CodeblockCustomizer#84]
When I export to PDF, I find that the code block is not expanded by default when it is selected to be collapsed, should the default behavior when exporting be changed to expand?

**Comment by mugiwara85** [comment]
Yepp, that's correct. But I could add a toggle, which if it is enabled would uncollapse all code blocks when printing, if that's ok?

**Comment by mugiwara85** [comment]
I added a toggle in the "Print to PDF" section, where you can switch it. It is not yet released. If you want to try it out, you can take the main.js file, and overwrite yours with it (create a backup before overwriting). I would appreciate a feedback.

**Comment by imingz** [comment]
Thank you, I think it's enough to use it now, and I look forward to the official launch of this feature in the future.

**Comment by mugiwara85** [comment]
Finally released. Officially available in version 1.2.7
