### ISSUE TITLE
Error displayed in reading mode

### ISSUE THREAD

**Issue by Tobeprmn** [mugiwara85/CodeblockCustomizer#85]
In reading mode, the code overlaps with the number of lines.
![1](https://github.com/mugiwara85/CodeblockCustomizer/assets/119318291/e8fe2f9f-de5b-4f4f-9ca6-ef2ca3b23839)

**Comment by mugiwara85** [comment]
I can't confirm that. Are you using some custom CSS? What theme are you using? Maybe that's causing problems

**Comment by Tobeprmn** [comment]
After turning off all css code, the problem persists. The theme I am using is AnuPpuccin.
![2](https://github.com/mugiwara85/CodeblockCustomizer/assets/119318291/9403ad3f-e734-408b-afed-7b0bcecb0250)

**Comment by mugiwara85** [comment]
Hi! Unfortunately, I still can't confirm it. I just installed AnuPpuccin Theme, but it is working fine for me. 
Try disabling all of your plugins, maybe one of them is causing this behavior. You could send me an example .md file. Maybe there are some invalid characters in the file itself. 
Do you see any errors in the console? (Ctrl+Shift+i)
You could also try to create a new Vault and install check if the problem still occurs. 
You need to somehow narrow down, what causing this, so I can reproduce it and fix it.

**Comment by Tobeprmn** [comment]
Thanks, I think I found the reason.

**Comment by mugiwara85** [comment]
> Thanks, I think I found the reason.

Just out of curiosity, what was caused this problem?

**Comment by Tobeprmn** [comment]
I apologize for the late reply, it's a problem caused by incompatibility between "better codeblock" and "codeblock customizer".
