### ISSUE TITLE
In reading mode, the highlight has a bug

### ISSUE THREAD

**Issue by 1607941875** [mugiwara85/CodeblockCustomizer#88]
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/59784883/f645227b-f43b-4e22-b167-4e4decaa8026)

source file 
[14. test.md](https://github.com/user-attachments/files/15813475/14.test.md)

**Comment by mugiwara85** [comment]
Yes, I also noticed that. It is already fixed in the upcoming release, which will be released either today or tomorrow.
