### ISSUE TITLE
In reading mode, is it possible to add a horizontal scroll bar that prevents code from wrapping?

### ISSUE THREAD

**Issue by 1607941875** [mugiwara85/CodeblockCustomizer#89]
like this
![45ced890792598b9970d1f888cc2c457_MD5](https://github.com/mugiwara85/CodeblockCustomizer/assets/59784883/716f5697-94fa-4fde-b77b-b8ff0b2840a0)

**Comment by mugiwara85** [comment]
you mean to unwrap code like this?
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/bafd3e9a-7079-468c-84a4-d60d418b71f5)
Also coming in the upcoming release :)

**Comment by 1607941875** [comment]
nice

**Comment by mugiwara85** [comment]
@1607941875 New version is available :)
