### ISSUE TITLE
the sponsor entrance is wrong

### ISSUE THREAD

**Issue by code-tomorrow** [mugiwara85/CodeblockCustomizer#90]
the sponsor channel is wrong, please check!

**Comment by mugiwara85** [comment]
Hi @code-tomorrow Which one do you mean?
This:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/d718461a-fcd5-4393-9ee9-7f0f5a02dfb3)
Or the other one at the bottom of the README:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/faaaa853-6848-42be-ba7f-d33829c46137)
I just tried both of them, and they work for me. They bring you to: https://buymeacoffee.com/thepirateking

Do you get an error?

**Comment by code-tomorrow** [comment]
There was something wrong with those two links, but now it is working properly.
