### ISSUE TITLE
[FR] Is it possible to provide a command to select the code block where the caret locates in.

### ISSUE THREAD

**Issue by XMB-7** [mugiwara85/CodeblockCustomizer#97]
For indenting a code block into a list, selecting the whole code block is required, followed by pressing `tab` multiple times.
It would be much handier when a command is provided to do the first step, i.e. selecting the whole code block, especially when the code block is too long.
Or does any other plugin have provided similar command? Thanks.

**Comment by mugiwara85** [comment]
By caret you mean the cursor, right? But yes, it is possible. Should the command just select the text, or also indent it? If it should also indent it one level, I could add a second command to unindent one level. Or if you say, it is enough to just for selecting text, then I could that as well. In this case, should be this a command, or a button, like the delete code button?

**Comment by XMB-7** [comment]
It's a great idea to have two commands for selecting text then un-/indenting one level and one button for only selecting the text.
But as for the button, maybe should add an option for users to choose to display it or not.

**Comment by mugiwara85** [comment]
Of course. I try to make everything optional :)

**Comment by mugiwara85** [comment]
Available in version 1.2.8
