### ISSUE TITLE
Render not effect in reading mode

### ISSUE THREAD

**Issue by yifan0414** [mugiwara85/CodeblockCustomizer#98]
When I highlight some line in edit mode, it effect immediately, but not effect in reading mode. I should click another document and then back to, it's normally.

Test in obsidian 1.6.7, sandbox
CodeblockCustomizer 1.2.7
![image](https://github.com/user-attachments/assets/0e78bbb7-6cca-4405-9a66-019a239ca889)

**Comment by mugiwara85** [comment]
Yes, I know, I haven't found a solution for this. This happens, because this is how Obsidian works. Changing the highlight parameters, does not trigger a rerender for reading mode, because Obsidian doesn't recognize that text as parameters.

**Comment by yifan0414** [comment]
@mugiwara85 Thanks for reply, I also have a question. Why the first line left align default, even i add some space(only in reading mode).

edit mode
![image](https://github.com/user-attachments/assets/4a3267cb-0701-4c62-91e1-e28ce6837572)

reading mode
![image](https://github.com/user-attachments/assets/ecf4aa15-a0b6-424e-bb83-0aa27b546e10)

**Comment by mugiwara85** [comment]
@yifan0414 That is probably a bug. It has probably to do something with the fold indicator in reading view. I am already working on a new version. I will fix this also before the next release.

**Comment by mugiwara85** [comment]
It is fixed now. I want to do 1-2 other things, and then it gets released.

**Comment by mugiwara85** [comment]
Fixed in version 1.2.8
