### ISSUE TITLE
Is it possible to add a separate control button for 'Unwrap code' to each code block?

### ISSUE THREAD

**Issue by 1607941875** [mugiwara85/CodeblockCustomizer#99]
Like this
![Jul-31-2024 19-50-33](https://github.com/user-attachments/assets/16be338e-0eed-4072-a115-f1809a19921a)

**Comment by mugiwara85** [comment]
Yes, I think it is. I will implement this before the next release.

**Comment by mugiwara85** [comment]
Available in version 1.2.8
